### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by lukasbystricky** [eybmv/felix-salten_bambi_whittaker-chambers#1]
- [x] Some typos in long description:
- enviornmental -> environmental
- generes -> genres
- "and learns have to survive He:the name given to men" should maybe be "and learns how to survive ”He“–the name given to men."

- [x] In the scans and transcription there's a foreword. I guess you decided to cut that? In that case there's no additional front matter so you can remove the half title page. 
- [x] I don't know if this is actually stated in the manual, but typically we include a reference and link to the author's name somewhere in the long description.
- [x] Should "Children’s" be added as an se:subject? (Maybe not, that's just a guess)

**Comment by eybmv** [comment]
re: forward -- Alex told the initial taker for Bambi to cut it, so I maintained that; unless you two would rather I add it back in. I had the half title page bc Bambi has a subtitle, unless (in the case of no forward) it would be in the metadata only 

re: last name -- it's stated that the first occurrence has a link, but not that it's convention to name drop. Will keep that in mind for the future! As this is the first novel by Salten to be hosted by SE, I'm guessing I just anticipate what the link would look like

**Comment by lukasbystricky** [comment]
Ah you're right, I missed that in the discussion. You should still remove the half title page. It's one of the quirks of SE that if there's no front matter, then if there's a subtitle it only show up in the metadata. 

And yeah, you can just guess what the link will be. It'll be automatically created. I don't know why that's not stated in the manual, but it definitely seems to be the convention. (And I vaguely recall being told to add an author link in one of my early productions.)

**Comment by eybmv** [comment]
Okay; thanks for that clarification! Done and pushed.
